# created by lesomras on 2026-5-30
"""..."""


class MopplotException(Exception): ...


class TypeException(MopplotException): ...


class InvalidValueException(MopplotException): ...


class PatternLexerException(MopplotException): ...


class TraitException(MopplotException): ...


class TraitFieldException(MopplotException): ...


class TraitPathException(MopplotException): ...


class TraitLibException(MopplotException): ...


class SyntaxException(MopplotException): ...


class MopplotDocException(MopplotException): ...
